ekf::EKF
float ekf::EKF::dt
Intervalo de tempo para integração
Referenced by integrationOfStates, predictionStage, telemetria, updatefi, updateOfMeasurements.
Eigen::Vector3f ekf::EKF::accel
Vetor com as medidas do aceleromeotro
Referenced by begin, integrationOfStates, predictionStage, telemetria, updateF_G, updateStates.
Eigen::Vector3f ekf::EKF::localGravity
Vetor de graviade escrita no sistema local.
Eigen::Vector3f ekf::EKF::navegationGravity
Gravidade no sistema de navegação
Referenced by integrationOfStates, updateStates.
Eigen::Vector3f ekf::EKF::gyro
Vetor com as medidas do giroscopios
Referenced by begin, integrationOfStates, telemetria, updateF_G.
Eigen::Vector3f ekf::EKF::mag
Vetor com as medidas do magnetometros
Referenced by begin, predictionStage, telemetria.
Eigen::Vector3f ekf::EKF::magOrthogonalGrav
Vetor com as medias do magnetometro sem as projeções na direção do vetor gravitacional
Referenced by predictionStage, updateH.
Eigen::Vector4f ekf::EKF::q
Quaternion de atitude
Referenced by integrationOfStates, telemetria, drone.Drone.updateStates, updateStates.
Eigen::Vector3f ekf::EKF::euler
Ângulos de Euler na convenção 3-2-1 Tait-Bryan
Referenced by telemetria, updateStates.
Eigen::Vector3f ekf::EKF::r
Vetor de estados estimados do EKF. O erros são: as três componetes da parte vetorial do quaternion, os três bias do giroscópio e as compoenentes da velocidade no sistema NED. [ q b r]Velocidade linear m/s
Referenced by integrationOfStates, updateOfMeasurements, updateStates.
Eigen::Vector3f ekf::EKF::deltar
Aceleração linear m/s^2
Referenced by predictionStage, updateStates.
Eigen::Matrix3f ekf::EKF::mcd
Matrix de cossenos diretores
Referenced by integrationOfStates, predictionStage, updateF_G, updateH, updateStates.
uint8_t ekf::EKF::messageGPS
Referenced by updateOfMeasurements.
uint8_t ekf::EKF::p
Número de linhas da matriz H. Assume 6 quando apenas a MARG está disponível e 9 quando MARG/GPS estão disponíveis.
Referenced by begin, integrationOfStates, updateF_G, updateOfMeasurements, updateStage, updateStates.
uint8_t ekf::EKF::n
Números de estados.
Referenced by begin, predictionStage, updatefi, updateOfMeasurements, updateStage.
float ekf::EKF::sigma_giro
Matriz de covariancia de processo A matriz Q é utilizada no produto de matrizes.
float ekf::EKF::sigma_bias_giro
float ekf::EKF::sigma_acel
float ekf::EKF::sigma_bias_acel
float ekf::EKF::sigma_mag
float ekf::EKF::sigma_vel
const Eigen::MatrixXf ekf::EKF::Q
Referenced by predictionStage.
const Eigen::MatrixXf ekf::EKF::R
Matriz de covariancia de medidas.
Referenced by updateStage.
Eigen::MatrixXf ekf::EKF::F
Matrix de estados linearizada
Referenced by begin, updateF_G, updatefi.
Eigen::MatrixXf ekf::EKF::fi
Matriz Jacobiana dos estados
Referenced by predictionStage, updatefi.
Eigen::MatrixXf ekf::EKF::G
Matriz G de ruido do processo
Referenced by begin, predictionStage, updateF_G.
Eigen::MatrixXf ekf::EKF::P
Matriz Covariancia
Referenced by predictionStage, updateStage.
Eigen::MatrixXf ekf::EKF::H
Matriz sensibilidade
Referenced by begin, updateH, updateStage.
Eigen::MatrixXf ekf::EKF::K
Ganho de Kalman
Referenced by updateStage.
Eigen::VectorXf ekf::EKF::deltaChi
Vetor de estados perturbados do estados estimados do EKF. deltaChi possui dimensão n+1, o primeiro elemento não é calculado pelo filtro mas computado na ().
Referenced by updateStage, updateStates.
Eigen::VectorXf ekf::EKF::deltaYObs
Erro das observações
Referenced by updateH, updateOfMeasurements, updateStage.
ekf::EKF::EKF()
void ekf::EKF::begin()
Inicializacao do filtro de Kalman.
Inicializa e configura:o GPS, a classe timeClass, instancia os sensores accel, gyro e mag; e Configura os valores padrões da matrizes F, G e H.
References accel, TIME::begin, IMU::begin, F, G, gpsSetup, gyro, H, mag, n, p.
Referenced by setup.
void ekf::EKF::loopEKF()
Loop do Filtro de Kalaman
References predictionStage, updateH, updateOfMeasurements, updateStage.
Referenced by core_1.
void ekf::EKF::updateOfMeasurements()
Atualiza a medicao a partir dos sensores da unidade Margin e GPS.
Faz a leitura dos sensores da MARG atualizando os vetores accel, gyro e mag e ElaspsedTime dt. ubxMessage.navVelned possui as medidas em centimetros
References TIME::computeElapsedTime, deltaYObs, dt, messageGPS, MT_NAV_POSLLH, MT_NAV_VELNED, MT_NONE, n, UBXMessage::navVelned, p, processGPS, r, IMU::readSensor, ubxMessage, NAV_VELNED_STRUCT::velD, NAV_VELNED_STRUCT::velE, NAV_VELNED_STRUCT::velN.
Referenced by loopEKF.
void ekf::EKF::updateInovations()
void ekf::EKF::integrationOfStates()
Observações preditasIntegra os estado q e r;.
References accel, dt, gyro, mcd, navegationGravity, p, q, r.
Referenced by predictionStage.
void ekf::EKF::updateStates()
Atualiza os estados predidos com os erros estimados.
References IMU::_biasAccel, IMU::_biasGyro, accel, deltaChi, deltar, euler, mcd, navegationGravity, p, q, r.
Referenced by updateStage.
void ekf::EKF::predictionStage()
Integra os estados e a matriz de covariancia a priori do filtro.
References accel, deltar, dt, fi, G, integrationOfStates, mag, magOrthogonalGrav, mcd, n, P, Q, updateF_G, updatefi.
Referenced by loopEKF.
void ekf::EKF::updateStage()
Etapa de atualização.
References deltaChi, deltaYObs, H, K, n, p, P, R, updateStates.
Referenced by loopEKF.
void ekf::EKF::updateF_G()
Atualiza matrix lineariza de estados F e a matrix G.
References accel, F, G, gyro, mcd, p.
Referenced by predictionStage.
void ekf::EKF::updateH()
Atualiza matrix de sessitividade H. g Vetor gravitacional predito. m Campo magnético predito.
References deltaYObs, H, magOrthogonalGrav, mcd.
Referenced by loopEKF.
void ekf::EKF::updatefi()
Futuras AtividadesOportunidade de otimização. Talves, na programação, a matrix F não precise existir e seja absorvida pela matrix fi.
References dt, F, fi, n.
Referenced by predictionStage.
void ekf::EKF::calibrationMethods(gpio_num_t &_porta_led)
Metodos de calibracao _porta_led [description]
References IMU::calibracaoMagnetometro, IMU::calibraGyro, TIME::computeElapsedTime.
Referenced by setup.