TIME
uint8_t TIME::timeVectorIndex
Indice do vetor.
Referenced by begin, computeElapsedTime.
uint64_t TIME::timeVector[2][2]
Vetor com as ultimas duas medidas.
Referenced by begin, computeElapsedTime.
TIME::TIME()
Instância da classe Time.
Utilizando o temporizador de alta resolução. timer esp_timer_get_time()
References begin.
float TIME::computeElapsedTime()
Retorna o valor do tempo decorrido desde a última requisição.
float de tempo decorrido em segundos. esp_timer_get_time() Computa o tempo decorrido em ms desde a Inicialização.
References timeVector, timeVectorIndex.
Referenced by ekf::EKF::calibrationMethods, ekf::EKF::updateOfMeasurements.
void TIME::begin()
Inicialização da classe Time.
References timeVector, timeVectorIndex.
Referenced by ekf::EKF::begin, TIME.