GPS.h
NAV_VELNED
RATE_1
NAV_MODE_1G
_ubxMsgType
const unsigned char UBX_HEADER[][]
Referenced by processGPS.
const unsigned char NAV_POSLLH_HEADER[][]
Referenced by processGPS.
const unsigned char NAV_VELNED_HEADER[][]
Referenced by processGPS.
const unsigned char NAV_PVT_HEADER[][]
PacketData data
Referenced by METODOSCALIBRACAO::calibracaoAcelerometro.
UBXMessage ubxMessage
Referenced by ekf::EKF::updateOfMeasurements.
HardwareSerial GPSSERIAL(1)
Referenced by gps_imprime, gpsSetup, processGPS.
void gpsSetup()
References GPSSERIAL.
Referenced by ekf::EKF::begin.
void calcChecksum(unsigned char *CK, int msgSize)
Referenced by processGPS.
boolean compareMsgHeader(const unsigned char *msgHeader)
Referenced by processGPS.
int processGPS()
References calcChecksum, compareMsgHeader, GPSSERIAL, MT_NAV_POSLLH, MT_NAV_VELNED, MT_NONE, NAV_POSLLH_HEADER, NAV_VELNED_HEADER, UBX_HEADER.
Referenced by gps_imprime, ekf::EKF::updateOfMeasurements.
void gps_imprime()
References GPSSERIAL, MT_NAV_POSLLH, MT_NAV_VELNED, UBXMessage::navVelned, processGPS, NAV_VELNED_STRUCT::velD.